### ISSUE TITLE
remove_prefix/remove_suffix return nil with non-existing prefix/suffix

### ISSUE THREAD

**Issue by matthieu-foucault** [bbatsov/powerpack#27]
```
> 'foo'.remove_prefix('bar')
 => nil 
```

I would expect this method to return the original string if the prefix/suffix is not in the string.
If returning nil is the expected behavior, this should be documented.
I can make the PR, just tell me which solution you favor.

**Comment by bbatsov** [comment]
Yeah, we should change this. It was likely an oversight as I hate `nil` return values.
