### ISSUE TITLE
Array#union and Array#difference

### ISSUE THREAD

**Issue by Ana06** [bbatsov/powerpack#33]
I have implemented an `Array#union` and `Array#difference` in C and I sent some months ago two PRs to Ruby core:

- https://github.com/ruby/ruby/pull/1747
- https://github.com/ruby/ruby/pull/1758

Although `array1 | array2` is already available in Ruby, `array1.union array2` is much more readable and elegant, following the _easy to use and to read_ Ruby principle. It also supports more than two arrays, and for more than two arrays this C implementation is more efficient than `|`. It is also coherent with `Array#concat`

Although I would really like to see this code in Ruby core, it seems that this won't happen. There is an issue in Ruby: https://bugs.ruby-lang.org/issues/14097 Here someone against having this method in Ruby suggested that I create my own gem for that. I really don't see the point in creating a gem only for that, but this project may be a good place for it. :blush:

I could send a PR if you want the methods here. That would imply having C code in this gem.

**Comment by bbatsov** [comment]
@Ana06 Sorry for the slow response!

I like those suggestions, I'm just wary of using C extensions - we'd always need to have some fallback to pure Ruby, so those methods would work on alternative runtimes.

PR welcome!

**Comment by Ana06** [comment]
It got merged in Ruby: https://github.com/ruby/ruby/pull/1747! :tada: So there is no need to add it here anymore. Thanks anyway :kissing_heart:

**Comment by bbatsov** [comment]
Great news! 

A problem that solves itself - sounds like a job for me! 🤣
