### ISSUE TITLE
Most tests have been disabled 

### ISSUE THREAD

**Issue by chocolateboy** [bbatsov/powerpack#34]
#30 appears to have disabled almost all tests. There used to be [over a hundred](https://travis-ci.org/bbatsov/powerpack/jobs/254080953), and now there are [13](https://travis-ci.org/bbatsov/powerpack/jobs/273430942).

The only tests that are running are running by mistake due to typos, namely:

`spec/powerpack/enumerable/exactly_spec.rb` starts with:

```ruby
unless Enumerable.method_defined? :exactly
```

which should presumably be:

```ruby
unless Enumerable.method_defined? :exactly?
``` 

and `spec/powerpack/enumerable/several_spec.rb` starts with:

```ruby
unless Enumerable.method_defined? :several
```
which should presumably be:

```ruby
unless Enumerable.method_defined? :several?
```
If these two typos are "fixed", **zero** tests run. What is the purpose of these guards?

**Comment by bbatsov** [comment]
Hmm, it seems I overlooked them in that PR. Those should be removed.
